services:
  homecloud:
    build:
      context: ..
      dockerfile: server/Dockerfile
    ports:
      - "7736:7736/tcp"
      - "7736:7736/udp"
    volumes:
      - ${HC_DATA_PATH:-~/HomeCloud}:/data
    environment:
      - HC_DATA_DIR=/data
      - HC_CACHE_DIR=/tmp/hcServerCache
      - PASSPHRASE=${PASSPHRASE}
      - CREDS_BASE64=${CREDS_BASE64:-}
      - CREDS_PATH=${CREDS_PATH:-}
      - API_SERVER_URL=${API_SERVER_URL:-}
    restart: unless-stopped
